### ISSUE TITLE
rocminfo 5.1.3 segfaults in hsa_init() with amdgpu (Linux 5.19.x / RX 6750XT) 

### ISSUE THREAD

**Issue by admnd** [RadeonOpenCompute/rocminfo#57]
Symptoms:
```
$ rocminfo 
ROCk module is loaded
Segmentation fault
```

In more details:
```
$ gdb /usr/bin/rocminfo 
GNU gdb (Gentoo 12.1 vanilla) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/rocminfo...
Reading symbols from /usr/lib/debug//usr/bin/rocminfo.debug...
(gdb) 
(gdb) run
Starting program: /usr/bin/rocminfo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
ROCk module is loaded

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7db56e7 in hsa_init () at /usr/src/debug/dev-libs/rocr-runtime-5.1.3/ROCR-Runtime-rocm-5.1.3/src/core/common/hsa_table_interface.cpp:67
67      hsa_status_t HSA_API hsa_init() { return coreApiTable->hsa_init_fn(); }

(gdb) display coreApiTable
1: coreApiTable = (const CoreApiTable *) 0x0

(gdb) bt
#0  0x00007ffff7db56e7 in hsa_init () at /usr/src/debug/dev-libs/rocr-runtime-5.1.3/ROCR-Runtime-rocm-5.1.3/src/core/common/hsa_table_interface.cpp:67
#1  0x000055555555d7a2 in main (argc=1, argv=0x7fffffffd8c8) at /usr/src/debug/dev-util/rocminfo-5.1.3/rocminfo-rocm-5.1.3/rocminfo.cc:1141
```

No deep investigation done, however rocm-smi seems functional:

```
 $ rocm-smi 
======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp   AvgPwr  SCLK    MCLK   Fan  Perf  PwrCap  VRAM%  GPU%  
0    39.0c  8.0W    500Mhz  96Mhz  0%   auto  220.0W   18%   3%    
================================================================================
============================= End of ROCm SMI Log ==============================
```

amdgpu related kernel log:
```
[    6.291237] [drm] amdgpu kernel modesetting enabled.
[    6.295804] amdgpu: Ignoring ACPI CRAT on non-APU system
[    6.295806] amdgpu: Virtual CRAT table created for CPU
[    6.295811] amdgpu: Topology: Add CPU node
[    6.295955] amdgpu 0000:2f:00.0: vgaarb: deactivate vga console
[    6.295985] amdgpu 0000:2f:00.0: enabling device (0006 -> 0007)
[    6.297556] amdgpu 0000:2f:00.0: amdgpu: Fetched VBIOS from VFCT
[    6.297557] amdgpu: ATOM BIOS: 113-D5270300-KXT
[    6.297565] amdgpu 0000:2f:00.0: amdgpu: Trusted Memory Zone (TMZ) feature disabled as experimental (default)
[    6.297591] amdgpu 0000:2f:00.0: amdgpu: VRAM: 12272M 0x0000008000000000 - 0x00000082FEFFFFFF (12272M used)
[    6.297592] amdgpu 0000:2f:00.0: amdgpu: GART: 512M 0x0000000000000000 - 0x000000001FFFFFFF
[    6.297593] amdgpu 0000:2f:00.0: amdgpu: AGP: 267894784M 0x0000008400000000 - 0x0000FFFFFFFFFFFF
[    6.297627] [drm] amdgpu: 12272M of VRAM memory ready
[    6.297627] [drm] amdgpu: 64377M of GTT memory ready.
[    6.297815] Loading firmware: amdgpu/navy_flounder_sos.bin
[    6.298824] Loading firmware: amdgpu/navy_flounder_ta.bin
[    6.299416] amdgpu 0000:2f:00.0: amdgpu: PSP runtime database doesn't exist
[    6.299419] amdgpu 0000:2f:00.0: amdgpu: PSP runtime database doesn't exist
[    8.354819] Loading firmware: amdgpu/navy_flounder_smc.bin
[    8.355873] amdgpu 0000:2f:00.0: amdgpu: STB initialized to 2048 entries
[    8.355915] Loading firmware: amdgpu/navy_flounder_dmcub.bin
[    8.356369] Loading firmware: amdgpu/navy_flounder_pfp.bin
[    8.357050] Loading firmware: amdgpu/navy_flounder_me.bin
[    8.357622] Loading firmware: amdgpu/navy_flounder_ce.bin
[    8.358079] Loading firmware: amdgpu/navy_flounder_rlc.bin
[    8.358441] Loading firmware: amdgpu/navy_flounder_mec.bin
[    8.358976] Loading firmware: amdgpu/navy_flounder_mec2.bin
[    8.359944] Loading firmware: amdgpu/navy_flounder_sdma.bin
[    8.360216] Loading firmware: amdgpu/navy_flounder_vcn.bin
[    8.360883] amdgpu 0000:2f:00.0: amdgpu: Will use PSP to load VCN firmware
[    8.517196] amdgpu 0000:2f:00.0: amdgpu: RAS: optional ras ta ucode is not available
[    8.531190] amdgpu 0000:2f:00.0: amdgpu: SECUREDISPLAY: securedisplay ta ucode is not available
[    8.531210] amdgpu 0000:2f:00.0: amdgpu: smu driver if version = 0x0000000e, smu fw if version = 0x00000012, smu fw program = 0, version = 0x00413500 (65.53.0)
[    8.531212] amdgpu 0000:2f:00.0: amdgpu: SMU driver if version not matched
[    8.531240] amdgpu 0000:2f:00.0: amdgpu: use vbios provided pptable
[    8.589463] amdgpu 0000:2f:00.0: amdgpu: SMU is initialized successfully!
[    8.593333] snd_hda_intel 0000:2f:00.1: bound 0000:2f:00.0 (ops amdgpu_dm_audio_component_bind_ops [amdgpu])
[    8.749752] kfd kfd: amdgpu: Allocated 3969056 bytes on gart
[    8.749934] amdgpu: sdma_bitmap: ffff
[    8.749974] amdgpu: Virtual CRAT table created for GPU
[    8.750092] amdgpu: Topology: Add dGPU node [0x73df:0x1002]
[    8.750093] kfd kfd: amdgpu: added device 1002:73df
[    8.750111] amdgpu 0000:2f:00.0: amdgpu: SE 2, SH per SE 2, CU per SH 10, active_cu_number 40
[    8.750153] amdgpu 0000:2f:00.0: amdgpu: ring gfx_0.0.0 uses VM inv eng 0 on hub 0
[    8.750153] amdgpu 0000:2f:00.0: amdgpu: ring comp_1.0.0 uses VM inv eng 1 on hub 0
[    8.750154] amdgpu 0000:2f:00.0: amdgpu: ring comp_1.1.0 uses VM inv eng 4 on hub 0
[    8.750155] amdgpu 0000:2f:00.0: amdgpu: ring comp_1.2.0 uses VM inv eng 5 on hub 0
[    8.750155] amdgpu 0000:2f:00.0: amdgpu: ring comp_1.3.0 uses VM inv eng 6 on hub 0
[    8.750155] amdgpu 0000:2f:00.0: amdgpu: ring comp_1.0.1 uses VM inv eng 7 on hub 0
[    8.750156] amdgpu 0000:2f:00.0: amdgpu: ring comp_1.1.1 uses VM inv eng 8 on hub 0
[    8.750156] amdgpu 0000:2f:00.0: amdgpu: ring comp_1.2.1 uses VM inv eng 9 on hub 0
[    8.750157] amdgpu 0000:2f:00.0: amdgpu: ring comp_1.3.1 uses VM inv eng 10 on hub 0
[    8.750157] amdgpu 0000:2f:00.0: amdgpu: ring kiq_2.1.0 uses VM inv eng 11 on hub 0
[    8.750158] amdgpu 0000:2f:00.0: amdgpu: ring sdma0 uses VM inv eng 12 on hub 0
[    8.750158] amdgpu 0000:2f:00.0: amdgpu: ring sdma1 uses VM inv eng 13 on hub 0
[    8.750159] amdgpu 0000:2f:00.0: amdgpu: ring vcn_dec_0 uses VM inv eng 0 on hub 1
[    8.750159] amdgpu 0000:2f:00.0: amdgpu: ring vcn_enc_0.0 uses VM inv eng 1 on hub 1
[    8.750160] amdgpu 0000:2f:00.0: amdgpu: ring vcn_enc_0.1 uses VM inv eng 4 on hub 1
[    8.750160] amdgpu 0000:2f:00.0: amdgpu: ring jpeg_dec uses VM inv eng 5 on hub 1
[    8.751156] amdgpu 0000:2f:00.0: amdgpu: Using BACO for runtime pm
[    8.751347] [drm] Initialized amdgpu 3.47.0 20150101 for 0000:2f:00.0 on minor 0
[    8.755569] fbcon: amdgpudrmfb (fb0) is primary device
[    8.866262] amdgpu 0000:2f:00.0: [drm] fb0: amdgpudrmfb frame buffer device
```

Will test with some variations (kernel version, etc).

**Comment by admnd** [comment]
Issue seems to traceback to my own setup and more specifically to LTO. Rebuilding my userland without any LTO options active in GCC solves this issue. Seems the optimizer is a bit too aggressive with singletons... (See  variable LinkAtLoadOrFirstTranslationUnitAccess defined in hsa_table_interface.cpp around line 64).

**Comment by admnd** [comment]
Closed, not a bug in itself.
